### ISSUE TITLE
Importing code to MBMP v13.0.9 sheets breaks source function

### ISSUE THREAD

**Issue by JNorwood82** [Seneschal55/Personal-Coding#1]
I have a Kenku cleric of the Mind, so need this info for MBMP's sheet, but importing the file breaks the source selection function of the sheet. Please advise

**Comment by kwhite551** [comment]
This code is meant to be my own use and made on my own time. The reason it's breaking is because the code is unfinished and I haven't taken the time to bug test what is already there. I recommend finding someone else's code of this if you can.

**Comment by JNorwood82** [comment]
Fair enough.
